dev

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,34 +10,57 @@ runs:
     - run: |
         set -eu
         if ! command -v bash >/dev/null; then
+          set -x
+          install=''
           if grep -Eq '^ID=alpine' /etc/os-release; then
-            printf '::group::Install packages required for checkout-action (bash)\n'
-            # NB: sync with apk_install in main.sh
-            if command -v sudo >/dev/null; then
-              sudo apk --no-cache add bash
-            elif command -v doas >/dev/null; then
-              doas apk --no-cache add bash
-            else
-              apk --no-cache add bash
-            fi
-            printf '::endgroup::\n'
+            install='apk'
           elif grep -Eq '^ID_LIKE=.*openwrt' /etc/os-release; then
-            printf '::group::Install packages required for checkout-action (bash)\n'
-            # NB: sync with opkg_install in main.sh
-            if command -v sudo >/dev/null; then
-              sudo mkdir -p /var/lock
-              sudo opkg update
-              sudo opkg install bash
-            else
-              mkdir -p /var/lock
-              opkg update
-              opkg install bash
-            fi
-            printf '::endgroup::\n'
-          else
-            printf '::error::checkout-action requires bash\n'
-            exit 1
+            install='opkg'
           fi
+          case "${install}" in
+            apk)
+              printf '::group::Install packages required for checkout-action (bash)\n'
+              # NB: sync with apk_install in main.sh
+              if command -v sudo >/dev/null; then
+                sudo apk --no-cache add bash
+              elif command -v doas >/dev/null; then
+                doas apk --no-cache add bash
+              else
+                apk --no-cache add bash
+              fi
+              printf '::endgroup::\n'
+              ;;
+            opkg)
+              printf '::group::Install packages required for checkout-action (bash)\n'
+              # NB: sync with opkg_install in main.sh
+              if command -v sudo >/dev/null; then
+                # https://github.com/openwrt/openwrt/issues/16935
+                if command -v opkg >/dev/null; then
+                  sudo mkdir -p /var/lock
+                  sudo opkg update
+                  sudo opkg install bash
+                else
+                  sudo apk update
+                  sudo apk --no-cache add bash
+                fi
+              else
+                # https://github.com/openwrt/openwrt/issues/16935
+                if command -v opkg >/dev/null; then
+                  mkdir -p /var/lock
+                  opkg update
+                  opkg install bash
+                else
+                  apk update
+                  apk --no-cache add bash
+                fi
+              fi
+              printf '::endgroup::\n'
+              ;;
+            *)
+              printf '::error::checkout-action requires bash\n'
+              exit 1
+              ;;
+          esac
         fi
       shell: sh
       if: runner.os == 'Linux'
