Improve comments and diagnostics

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -13,6 +13,13 @@ runs:
   using: composite
   steps:
     - run: |
+        bail() {
+          printf '::error::checkout-action: %s\n' "$*"
+          exit 1
+        }
+        warn() {
+          printf '::warning::checkout-action: %s\n' "$*"
+        }
         if command -v /bin/grep >/dev/null; then
           grep=/bin/grep
         elif command -v /usr/bin/grep >/dev/null; then
@@ -20,17 +27,15 @@ runs:
         else
           grep=$(command -v grep)
           if [ -n "${HAS_TOKEN}" ]; then
-            printf '::error::grep is unavailable at standard location; found %s\n' "${grep}"
-            exit 1
+            bail "grep is unavailable at standard location; found ${grep}"
           else
-            printf '::warning::grep is unavailable at standard location; using %s\n' "${grep}"
+            warn "grep is unavailable at standard location; using ${grep}"
           fi
         fi
         # If /bin/sh is dash, environment variable containing % is not imported, but is fine
         # because it also means that it will not be exposed to subprocess.
         if /usr/bin/env | "${grep}" -Eq '^BASH_FUNC_'; then
-          printf '::error::bash function injection via BASH_FUNC_ environment variable is not allowed for security reasons\n'
-          exit 1
+          bail 'bash function injection via BASH_FUNC_ environment variable is not allowed for security reasons'
         fi
         if ! command -v bash >/dev/null; then
           if command -v /bin/sleep >/dev/null; then
@@ -40,10 +45,9 @@ runs:
           else
             sleep=$(command -v sleep)
             if [ -n "${HAS_TOKEN}" ]; then
-              printf '::error::sleep is unavailable at standard location; found %s\n' "${sleep}"
-              exit 1
+              bail "sleep is unavailable at standard location; found ${sleep}"
             else
-              printf '::warning::sleep is unavailable at standard location; using %s\n' "${sleep}"
+              warn "sleep is unavailable at standard location; using ${sleep}"
             fi
           fi
           retry() {
@@ -90,8 +94,7 @@ runs:
             fi
             printf '::endgroup::\n'
           else
-            printf '::error::checkout-action requires bash\n'
-            exit 1
+            bail 'this action requires bash'
           fi
         fi
         if command -v /bin/bash >/dev/null; then
@@ -99,10 +102,9 @@ runs:
         else
           bash=$(command -v bash)
           if [ -n "${HAS_TOKEN}" ]; then
-            printf '::error::bash is unavailable at standard location; found %s\n' "${bash}"
-            exit 1
+            bail "bash is unavailable at standard location; found ${bash}"
           else
-            printf '::warning::bash is unavailable at standard location; using %s\n' "${bash}"
+            warn "bash is unavailable at standard location; using ${bash}"
             "${bash}" --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
           fi
         fi
@@ -128,7 +130,7 @@ runs:
         if (Test-Path "Env:SHELLOPTS") { Remove-Item Env:\SHELLOPTS }
         if (Test-Path "Env:BASHOPTS") { Remove-Item Env:\BASHOPTS }
         if (Test-Path "Env:BASH_FUNC_*") {
-          Write-Output "::error::bash function injection via BASH_FUNC_ environment variable is not allowed for security reasons"
+          Write-Output "::error::checkout-action: bash function injection via BASH_FUNC_ environment variable is not allowed for security reasons"
           exit 1
         }
         $bash = (Get-Command bash).Path
@@ -138,10 +140,10 @@ runs:
           "C:\tools\cygwin\bin\bash.exe" {} # cygwin
           default {
             if ("$env:HAS_TOKEN" -ne "") {
-              Write-Output "::error::bash is unavailable at standard location; found $bash"
+              Write-Output "::error::checkout-action: bash is unavailable at standard location; found $bash"
               exit 1
             } else {
-              Write-Output "::warning::bash is unavailable at standard location; using $bash"
+              Write-Output "::warning::checkout-action: bash is unavailable at standard location; using $bash"
             }
           }
         }
@@ -157,10 +159,10 @@ runs:
             exit $code
           }
           if ($i -lt 10) {
-            Write-Output "::warning::installation failed due to bash startup failure (<https://github.com/actions/partner-runner-images/issues/169>); retrying..."
+            Write-Output "::warning::checkout-action: checkout failed due to bash startup failure (<https://github.com/actions/partner-runner-images/issues/169>); retrying..."
           }
         }
-        Write-Output "::error::installation failed due to bash startup failure (<https://github.com/actions/partner-runner-images/issues/169>); this maybe resolved by re-running job"
+        Write-Output "::error::checkout-action: checkout failed due to bash startup failure (<https://github.com/actions/partner-runner-images/issues/169>); this maybe resolved by re-running job"
         exit 1
       shell: pwsh
       env:
