Support using busybox instead of bash on Linux

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,34 +26,17 @@ runs:
           exit 1
         fi
         if ! command -v bash >/dev/null; then
-          if "${grep}" -Eq '^ID=alpine' /etc/os-release; then
-            printf '::group::Install packages required for checkout-action (bash)\n'
-            # NB: sync with apk_install in main.sh
-            if command -v sudo >/dev/null; then
-              sudo apk --no-cache add bash
-            elif command -v doas >/dev/null; then
-              doas apk --no-cache add bash
+          if command -v busybox >/dev/null; then
+            if command -v /bin/busybox >/dev/null; then
+              /bin/busybox sh "${GITHUB_ACTION_PATH:?}/main.sh"
             else
-              apk --no-cache add bash
+              printf '::warning::busybox is unavailable at standard location; using %s\n' "$(command -v busybox)"
+              busybox sh "${GITHUB_ACTION_PATH:?}/main.sh"
             fi
-            printf '::endgroup::\n'
-          elif "${grep}" -Eq '^ID_LIKE=.*openwrt' /etc/os-release; then
-            printf '::group::Install packages required for checkout-action (bash)\n'
-            # NB: sync with opkg_install in main.sh
-            if command -v sudo >/dev/null; then
-              sudo mkdir -p /var/lock
-              sudo opkg update
-              sudo opkg install bash
-            else
-              mkdir -p /var/lock
-              opkg update
-              opkg install bash
-            fi
-            printf '::endgroup::\n'
-          else
-            printf '::error::checkout-action requires bash\n'
-            exit 1
+            exit
           fi
+          printf '::error::checkout-action requires bash or busybox\n'
+          exit 1
         fi
         if command -v /bin/bash >/dev/null; then
           /bin/bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
