Clean up sys_install & add retry to bash install

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -21,54 +21,68 @@ runs:
           grep=$(command -v grep)
           printf '::warning::grep is unavailable at standard location; using %s\n' "${grep}"
         fi
+        # If /bin/sh is dash, environment variable containing % is not imported, but is fine
+        # because it also means that it will not be exposed to subprocess.
         if /usr/bin/env | "${grep}" -Eq '^BASH_FUNC_'; then
           printf '::error::bash function injection via BASH_FUNC_ environment variable is not allowed for security reasons\n'
           exit 1
         fi
         if ! command -v bash >/dev/null; then
-          install=''
-          if "${grep}" -Eq '^ID=alpine' /etc/os-release; then
-            install='apk'
-          elif "${grep}" -Eq '^ID_LIKE=.*openwrt' /etc/os-release; then
-            # https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164
-            if command -v apk >/dev/null; then
-              install='apk'
-            else
-              install='opkg'
-            fi
+          if command -v /bin/sleep >/dev/null; then
+            sleep=/bin/sleep
+          elif command -v /usr/bin/sleep >/dev/null; then
+            sleep=/usr/bin/sleep
+          else
+            sleep=$(command -v sleep)
+            printf '::warning::sleep is unavailable at standard location; using %s\n' "${sleep}"
           fi
-          case "${install}" in
-            apk)
-              printf '::group::Install packages required for checkout-action (bash)\n'
-              # NB: sync with apk_install in main.sh
-              if command -v sudo >/dev/null; then
-                sudo apk --no-cache add bash
-              elif command -v doas >/dev/null; then
-                doas apk --no-cache add bash
+          retry() {
+            for i in 1 2 3 4 5 6 7 8 9 10; do
+              if "$@"; then
+                return 0
               else
-                apk --no-cache add bash
+                "${sleep}" "${i}"
               fi
-              printf '::endgroup::\n'
-              ;;
-            opkg)
-              printf '::group::Install packages required for checkout-action (bash)\n'
-              # NB: sync with opkg_install in main.sh
-              if command -v sudo >/dev/null; then
-                sudo mkdir -p /var/lock
-                sudo opkg update
-                sudo opkg install bash
+            done
+            "$@"
+          }
+          if "${grep}" -Eq '^ID="?alpine"?$|^ID_LIKE=.*alpine' /etc/os-release; then
+            printf '::group::Install packages required for checkout-action (bash)\n'
+            # NB: sync with main.sh
+            if command -v /usr/bin/sudo >/dev/null; then
+              retry /usr/bin/sudo /sbin/apk --no-cache add bash
+            elif command -v /usr/bin/doas >/dev/null; then
+              retry /usr/bin/doas /sbin/apk --no-cache add bash
+            else
+              retry /sbin/apk --no-cache add bash
+            fi
+            printf '::endgroup::\n'
+          elif "${grep}" -Eq '^ID="?openwrt"?$|^ID_LIKE=.*openwrt' /etc/os-release; then
+            printf '::group::Install packages required for checkout-action (bash)\n'
+            # NB: sync with main.sh
+            # https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164
+            if command -v /usr/bin/apk >/dev/null; then
+              if command -v /usr/bin/sudo >/dev/null; then
+                retry /usr/bin/sudo /usr/bin/apk --no-cache add bash
               else
-                mkdir -p /var/lock
-                opkg update
-                opkg install bash
+                retry /usr/bin/apk --no-cache add bash
               fi
-              printf '::endgroup::\n'
-              ;;
-            *)
-              printf '::error::checkout-action requires bash\n'
-              exit 1
-              ;;
-          esac
+            else
+              if command -v /usr/bin/sudo >/dev/null; then
+                /usr/bin/sudo /bin/mkdir -p -- /var/lock
+                retry /usr/bin/sudo /bin/opkg update
+                retry /usr/bin/sudo /bin/opkg install bash
+              else
+                /bin/mkdir -p -- /var/lock
+                retry /bin/opkg update
+                retry /bin/opkg install bash
+              fi
+            fi
+            printf '::endgroup::\n'
+          else
+            printf '::error::checkout-action requires bash\n'
+            exit 1
+          fi
         fi
         if command -v /bin/bash >/dev/null; then
           /bin/bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
