Improve support for OpenWrt 25.12+

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,34 +26,49 @@ runs:
           exit 1
         fi
         if ! command -v bash >/dev/null; then
+          install=''
           if "${grep}" -Eq '^ID=alpine' /etc/os-release; then
-            printf '::group::Install packages required for checkout-action (bash)\n'
-            # NB: sync with apk_install in main.sh
-            if command -v sudo >/dev/null; then
-              sudo apk --no-cache add bash
-            elif command -v doas >/dev/null; then
-              doas apk --no-cache add bash
-            else
-              apk --no-cache add bash
-            fi
-            printf '::endgroup::\n'
+            install='apk'
           elif "${grep}" -Eq '^ID_LIKE=.*openwrt' /etc/os-release; then
-            printf '::group::Install packages required for checkout-action (bash)\n'
-            # NB: sync with opkg_install in main.sh
-            if command -v sudo >/dev/null; then
-              sudo mkdir -p /var/lock
-              sudo opkg update
-              sudo opkg install bash
+            # https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164
+            if command -v apk >/dev/null; then
+              install='apk'
             else
-              mkdir -p /var/lock
-              opkg update
-              opkg install bash
+              install='opkg'
             fi
-            printf '::endgroup::\n'
-          else
-            printf '::error::checkout-action requires bash\n'
-            exit 1
           fi
+          case "${install}" in
+            apk)
+              printf '::group::Install packages required for checkout-action (bash)\n'
+              # NB: sync with apk_install in main.sh
+              if command -v sudo >/dev/null; then
+                sudo apk --no-cache add bash
+              elif command -v doas >/dev/null; then
+                doas apk --no-cache add bash
+              else
+                apk --no-cache add bash
+              fi
+              printf '::endgroup::\n'
+              ;;
+            opkg)
+              printf '::group::Install packages required for checkout-action (bash)\n'
+              # NB: sync with opkg_install in main.sh
+              if command -v sudo >/dev/null; then
+                sudo mkdir -p /var/lock
+                sudo opkg update
+                sudo opkg install bash
+              else
+                mkdir -p /var/lock
+                opkg update
+                opkg install bash
+              fi
+              printf '::endgroup::\n'
+              ;;
+            *)
+              printf '::error::checkout-action requires bash\n'
+              exit 1
+              ;;
+          esac
         fi
         if command -v /bin/bash >/dev/null; then
           /bin/bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
