Improve platform support

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,21 +25,44 @@ jobs:
   tidy:
     uses: taiki-e/github-actions/.github/workflows/tidy.yml@main
 
-  checkout-action:
+  test:
     strategy:
       fail-fast: false
       matrix:
-        os:
-          - ubuntu-latest
-          - macos-latest
-          - windows-latest
+        include:
+          - os: ubuntu-20.04
+          - os: ubuntu-22.04
+          - os: ubuntu-24.04
+          - os: macos-12
+          - os: macos-13
+          - os: macos-14
+          - os: windows-2019
+          - os: windows-2019
+            bash: msys64
+          - os: windows-2019
+            bash: cygwin
+          - os: windows-2022
+          - os: windows-2022
+            bash: msys64
+          - os: windows-2022
+            bash: cygwin
     runs-on: ${{ matrix.os }}
     steps:
+      - run: |
+          printf 'C:\msys64\mingw32\bin\n' >>"${GITHUB_PATH}"
+          printf 'C:\msys64\usr\bin\n' >>"${GITHUB_PATH}"
+        if: matrix.bash == 'msys64'
+      - run: |
+          choco install --no-progress --requirechecksums cygwin
+          printf 'C:\tools\cygwin\bin\n' >>"${GITHUB_PATH}"
+          printf 'C:\tools\cygwin\usr\bin\n' >>"${GITHUB_PATH}"
+        if: matrix.bash == 'cygwin'
       - uses: taiki-e/checkout-action@main
       - uses: taiki-e/install-action@shellcheck
       - uses: taiki-e/install-action@shfmt
       - run: git ls-files
       - run: ./tools/tidy.sh
+        if: matrix.os != 'windows-2019'
   # For comparison
   actions-checkout:
     strategy:
@@ -76,6 +99,7 @@ jobs:
           - almalinux:8-minimal # glibc 2.28
           - almalinux:9 # glibc 2.34
           - almalinux:9-minimal # glibc 2.34
+          - centos:6 # glibc 2.12
           - centos:7 # glibc 2.17
           - opensuse/leap:latest # glibc 2.31 (as of leap 15.5)
           - opensuse/tumbleweed:latest # glibc 2.39 (as of 2024-04-18)
@@ -87,15 +111,20 @@ jobs:
     steps:
       - name: Install requirements (centos)
         run: |
-          set -eEuxo pipefail
+          set -CeEuxo pipefail
           # https://github.com/rust-lang/rust/pull/126352
           sed -i /etc/yum.repos.d/*.repo -e 's!^mirrorlist!#mirrorlist!' \
-          -e 's!^#baseurl=http://mirror.centos.org/!baseurl=https://vault.centos.org/!'
+            -e 's!^#baseurl=http://mirror.centos.org/!baseurl=https://vault.centos.org/!'
           sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf
+          if [[ "${{ matrix.container }}" == "centos:6" ]]; then
+            # CentOS 6's git (1.7.1) has no --local/--no-recurse-submodules.
+            # And even if we don't pass those flags, that version of git will not work
+            # anyway due to of "fatal: Couldn't find remote ref" error.
+            yum install -y openssh-clients perl perl-Error perl-TermReadKey rsync
+            rpm -i \
+              https://vault.ius.io/el6/x86_64/packages/p/perl-Git18-1.8.5.5-4.ius.el6.noarch.rpm \
+              https://vault.ius.io/el6/x86_64/packages/g/git18-1.8.5.5-4.ius.el6.x86_64.rpm
+          fi
         if: startsWith(matrix.container, 'centos')
-      - name: Install requirements (alpine)
-        run: apk --no-cache add bash
-        shell: sh
-        if: startsWith(matrix.container, 'alpine')
       - uses: taiki-e/checkout-action@main
       - run: git ls-files
